package com.darkube.pirate.types

enum class DetailsKey(val value: String) {
    APP_NOTIFICATION("APP_NOTIFICATION"),
    HIDE_ONLINE_STATUS("HIDE_ONLINE_STATUS"),
    CHAT_NOTIFICATION("KEY:CHAT_NOTIFICATION"),
    LAST_OPENED("KEY:CHAT_NOTIFICATION"),
}
