export const ERRORS = {
  JWT: {
    SECRET_NOT_DEFINED: 'SECRET_NOT_DEFINED',
    INVALID_OR_EXPIRED: 'INVALID_OR_EXPIRED',
  },
  AUTH: {
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
  },
  ACCOUNT: {
    ALREADY_EXISTS: 'ACCOUNT_ALREADY_EXISTS',
    USERNAME_ALREADY_EXISTS: 'ACCOUNT_WITH_USERNAME_ALREADY_EXISTS',
    EMAIL_ALREADY_EXISTS: 'ACCOUNT_WITH_EMAIL_ALREADY_EXISTS',
  },
  DUPLICATE_ENTRY_EXISTS: 'DUPLICATE_ENTRY_EXISTS',
  INVALID_REQUEST: 'INVALID_REQUEST',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
}
